CI: Switch to Ubuntu 24.04 for Clang job
The previous commit fails to build on 22.04, which is stuck with Clang 14.0.0.

Error: src/backends/PipeWire/PipeWire.cpp:347:28: error: no matching constructor for initialization of 'pipewire::Engine::Node'
          m_nodes.emplace(info->id, Node(id, name, static_cast< Direction >(direction)));
                                    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/backends/PipeWire/PipeWire.hpp:45:9: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
          struct Node {
                 ^
  src/backends/PipeWire/PipeWire.hpp:45:9: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 3 were provided
  src/backends/PipeWire/PipeWire.hpp:45:9: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 3 were provided